# Generated by Django 2.0.1 on 2018-01-17 09:50

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils
import finances.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an account name (e.g. KiwiBank Everyday)', max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(('model', django.contrib.auth.models.User), ('model', finances.models.Account), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_bal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cr', to='finances.Account')),
                ('dr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dr', to='finances.Account')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
