# Generated by Django 2.0.1 on 2018-01-17 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category of account or transaction', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='final_bal',
            new_name='final_balance',
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(help_text='Enter an account name (e.g. KiwiBank Everyday)', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acategory', to='finances.Category'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tcategory', to='finances.Category'),
        ),
    ]
