# Generated by Django 2.0.1 on 2018-01-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='transaction_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
