# Generated by Django 2.0.1 on 2018-01-22 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_auto_20180122_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, help_text='Enter a description (e.g. Savings)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
