# Generated by Django 2.0.1 on 2018-01-22 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_auto_20180122_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='transaction_file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['csv', 'CSV'], 'Upload file as a CSV')]),
        ),
    ]
