# Generated by Django 2.0.1 on 2018-01-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_auto_20180122_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, help_text='Enter a description (e.g. KiwiBank Everyday)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(help_text='Enter an account name (e.g. account number)', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category of account or transaction', max_length=255, primary_key=True, serialize=False),
        ),
    ]
